import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import generatedApiSidebar from './docs/api/sidebar';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const apisidebar = Array.isArray(generatedApiSidebar) ? generatedApiSidebar : [];

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Keep Guides minimal and focused
  tutorialSidebar: ['intro'],

  // API Documentation sidebar pulled from autogenerated OpenAPI docs
  apisidebar,

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
