basePath: /api/external/v1
definitions:
  apperror.Error:
    properties:
      formatted:
        additionalProperties: {}
        type: object
      issues:
        items:
          $ref: '#/definitions/apperror.ErrorIssue'
        type: array
      message:
        type: string
      success:
        type: boolean
    type: object
  apperror.ErrorIssue:
    properties:
      code:
        type: string
      expected: {}
      message:
        type: string
      path:
        items:
          type: string
        type: array
      received: {}
    type: object
  constants.DocumentIDEnvelope:
    properties:
      document_id:
        type: string
    type: object
  constants.IDEnvelope:
    properties:
      id:
        type: string
    type: object
  constants.ResponseBody:
    properties:
      data: {}
      errors: {}
      request_id:
        type: string
    type: object
  v1.activityTitleRequest:
    properties:
      activity_title:
        type: string
    required:
    - activity_title
    type: object
  v1.createOrganizationRequest:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  v1.generalDescriptionRequest:
    properties:
      activity_status:
        enum:
        - PLANNING
        - ONGOING
        type: string
      general_purpose:
        type: string
      organization:
        type: string
    required:
    - activity_status
    - general_purpose
    - organization
    type: object
  v1.grkCreditContributionRequest:
    properties:
      contribution_explanation:
        type: string
    type: object
  v1.loginRequest:
    properties:
      email:
        type: string
      password:
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  v1.mitigationActionRequest:
    properties:
      activity_title:
        $ref: '#/definitions/v1.activityTitleRequest'
      analyst:
        $ref: '#/definitions/v1.projectAnalystRequest'
      general_description:
        $ref: '#/definitions/v1.generalDescriptionRequest'
      grk_contribution:
        $ref: '#/definitions/v1.grkCreditContributionRequest'
      location:
        $ref: '#/definitions/v1.mitigationLocationRequest'
      project_duration:
        $ref: '#/definitions/v1.projectDurationRequest'
      representative:
        $ref: '#/definitions/v1.representativeContactRequest'
      spei_participant:
        $ref: '#/definitions/v1.speiParticipantIdentityRequest'
    required:
    - activity_title
    - analyst
    - general_description
    - grk_contribution
    - location
    - project_duration
    - representative
    - spei_participant
    type: object
  v1.mitigationLocationRequest:
    properties:
      district:
        type: string
      latitude:
        type: number
      longitude:
        type: number
      postal_code:
        type: string
      province:
        type: string
      sub_district:
        type: string
      village:
        type: string
    required:
    - district
    - latitude
    - longitude
    - postal_code
    - province
    - sub_district
    - village
    type: object
  v1.projectAnalystRequest:
    properties:
      implementation_barriers:
        type: string
      required_by_government_policy:
        type: string
    type: object
  v1.projectDurationRequest:
    properties:
      project_category:
        type: string
      start_date:
        type: string
    required:
    - project_category
    type: object
  v1.refreshRequest:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  v1.registerUserRequest:
    properties:
      email:
        type: string
      name:
        type: string
      organization_id:
        type: string
      password:
        minLength: 8
        type: string
    required:
    - email
    - name
    - organization_id
    - password
    type: object
  v1.representativeContactRequest:
    properties:
      email:
        type: string
      full_name:
        type: string
      organization:
        type: string
      phone_number:
        type: string
      position:
        type: string
    required:
    - email
    - full_name
    - organization
    - phone_number
    - position
    type: object
  v1.speiParticipantIdentityRequest:
    properties:
      address:
        type: string
      district:
        type: string
      email:
        type: string
      organization:
        type: string
      organization_type:
        type: string
      phone_number:
        type: string
      province:
        description: Location Detail
        type: string
      representative_name:
        description: Organization Representative Profile
        type: string
      representative_title:
        type: string
      role_in_mitigation:
        type: string
      spe_grk_ownership_ratio:
        maximum: 100
        minimum: 0
        type: integer
      sub_district:
        type: string
      village:
        type: string
      website:
        type: string
    required:
    - address
    - district
    - email
    - organization
    - organization_type
    - phone_number
    - province
    - representative_name
    - representative_title
    - role_in_mitigation
    - spe_grk_ownership_ratio
    - sub_district
    - village
    type: object
  v1.tokenPairResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
host: api.ekobelens.com
info:
  contact:
    name: Ekobelens-Labs
    url: https://github.com/ekobelens-labs
  description: Ekobelens Service API Docs.
  title: Ekobelens API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Authenticate user and return access and refresh tokens
      parameters:
      - description: Login payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.loginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/constants.ResponseBody'
            - properties:
                data:
                  $ref: '#/definitions/v1.tokenPairResponse'
                request_id:
                  type: string
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apperror.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.Error'
      summary: Login
      tags:
      - Auth
  /auth/refresh:
    post:
      consumes:
      - application/json
      description: Exchange a valid refresh token for a new token pair
      parameters:
      - description: Refresh payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.refreshRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/constants.ResponseBody'
            - properties:
                data:
                  $ref: '#/definitions/v1.tokenPairResponse'
                request_id:
                  type: string
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apperror.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.Error'
      summary: Refresh Token
      tags:
      - Auth
  /dram/chapter/{chapter}:
    post:
      consumes:
      - application/json
      description: |
        Create a new DRAM document chapter
        ## Chapter 1 JSON Payload to UI Form Field Mapping

        ### Activity Title Section (Step 1/8)

        | JSON Payload Field              | UI Form Field                  |
        | ------------------------------- | ------------------------------ |
        | `activity_title.activity_title` | Judul Kegiatan / Aksi Mitigasi |

        ### General Description Section (Step 2/8)

        | JSON Payload Field                    | UI Form Field                             |
        | ------------------------------------- | ----------------------------------------- |
        | `general_description.organization`    | Organisasi/Entitas                        |
        | `general_description.activity_status` | Status Kegiatan (Rencana/Sedang Berjalan) |
        | `general_description.general_purpose` | Tujuan Umum                               |

        ### SPEI Participant Identity Section (Step 3/8)

        | JSON Payload Field                         | UI Form Field                  |
        | ------------------------------------------ | ------------------------------ |
        | `spei_participant.organization`            | Organisasi/Entitas             |
        | `spei_participant.organization_type`       | Jenis Organisasi/Entitas       |
        | `spei_participant.role_in_mitigation`      | Peran dalam Aksi Mitigasi      |
        | `spei_participant.spe_grk_ownership_ratio` | Bagian Kepemilikan SPE-GRK (%) |
        | `spei_participant.representative_name`     | Nama Perwakilan                |
        | `spei_participant.representative_title`    | Jabatan                        |
        | `spei_participant.email`                   | Email                          |
        | `spei_participant.phone_number`            | Nomor Telepon                  |
        | `spei_participant.website`                 | Situs Web                      |
        | `spei_participant.address`                 | Alamat                         |
        | `spei_participant.province`                | Provinsi                       |
        | `spei_participant.district`                | Kabupaten/Kota                 |
        | `spei_participant.sub_district`            | Kecamatan                      |
        | `spei_participant.village`                 | Kodepos                        |

        ### Representative Contact Section (Step 4/8)

        | JSON Payload Field            | UI Form Field      |
        | ----------------------------- | ------------------ |
        | `representative.organization` | Organisasi/Entitas |
        | `representative.full_name`    | Nama Lengkap       |
        | `representative.position`     | Jabatan            |
        | `representative.email`        | Email              |
        | `representative.phone_number` | Nomor Telepon      |

        ### Mitigation Location Section (Step 5/8)

        | JSON Payload Field      | UI Form Field        |
        | ----------------------- | -------------------- |
        | `location.province`     | Provinsi             |
        | `location.district`     | Kabupaten/Kota       |
        | `location.sub_district` | Kecamatan            |
        | `location.village`      | Dusun/Desa/Kelurahan |
        | `location.postal_code`  | Kodepos              |
        | `location.longitude`    | Longitude            |
        | `location.latitude`     | Latitude             |

        ### Project Duration Section (Step 6/8)

        | JSON Payload Field                  | UI Form Field               |
        | ----------------------------------- | --------------------------- |
        | `project_duration.project_category` | Kategori Proyek             |
        | `project_duration.start_date`       | Tanggal Mulai Durasi Proyek |

        ### GRK Credit Contribution Section (Step 7/8)

        | JSON Payload Field                          | UI Form Field                                  |
        | ------------------------------------------- | ---------------------------------------------- |
        | `grk_contribution.contribution_explanation` | Penjelasan Kontribusi untuk Pembeli Kredit GRK |

        ### Project Analysis Section (Step 8/8)

        | JSON Payload Field                      | UI Form Field                                                  |
        | --------------------------------------- | -------------------------------------------------------------- |
        | `analyst.required_by_government_policy` | Apakah aksi mitigasi ini diwajibkan oleh kebijakan pemerintah? |
        | `analyst.implementation_barriers`       | Hambatan pelaksanaan                                           |
      parameters:
      - description: Chapter number
        enum:
        - 1
        - 2
        in: path
        name: chapter
        required: true
        type: integer
      - description: DRAM chapter payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.mitigationActionRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/constants.ResponseBody'
            - properties:
                data:
                  $ref: '#/definitions/constants.DocumentIDEnvelope'
                request_id:
                  type: string
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apperror.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/apperror.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.Error'
      security:
      - BearerAuth: []
      summary: Create DRAM Document Chapter
      tags:
      - DRAM
  /organization/:
    post:
      consumes:
      - application/json
      description: Create a new organization
      parameters:
      - description: Organization payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.createOrganizationRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/constants.ResponseBody'
            - properties:
                data:
                  $ref: '#/definitions/constants.IDEnvelope'
                request_id:
                  type: string
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apperror.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.Error'
      summary: Create Organization
      tags:
      - Organization
  /user/:
    post:
      consumes:
      - application/json
      description: Create a new user in an organization
      parameters:
      - description: User registration payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.registerUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/constants.ResponseBody'
            - properties:
                data:
                  $ref: '#/definitions/constants.IDEnvelope'
                request_id:
                  type: string
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apperror.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperror.Error'
      summary: Register User
      tags:
      - User
schemes:
- https
swagger: "2.0"
